# Generated by Django 6.1.1 on 2026-09-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(default='Sem marca', max_length=50),
            preserve_default=False,
        ),
    ]
