# Generated by Django 6.1.1 on 2026-09-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
